services:
  frontend:
    build:
      context: ./frontend
    container_name: filehub-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: filehub-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      PORT: 5000
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    container_name: filehub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: filehub
      POSTGRES_USER: filehub
      POSTGRES_PASSWORD: filehub_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: